### ISSUE TITLE
math library: Trigonometric functions don't work as expected

### ISSUE THREAD

**Issue by TheRetikGM** [FIT-IVS-segmentation-fault-core-dumped/IVS-projekt-2#19]
# Problem
Basically what the title says. Trigonometric functions return wrong values for some inputs. I have written additional tests showcasing this. For more details see changes in #18

**Comment by tmokenc** [comment]
Oh nice catch!
It's a bug in the `to_string` function where it does not round up to the whole part of the number, like `0.9` -> `0`
I'll work on this ASAP.
