### ISSUE TITLE
math: Reverse order of operands in root() function

### ISSUE THREAD

**Issue by TheRetikGM** [FIT-IVS-segmentation-fault-core-dumped/IVS-projekt-2#23]
Right now, I have to specially handle a `root` function in evaluation string, in order to pass arguments to it in reverse order. Reason is that, the user inputs as follows:

    3root27

But I need to convert it to:

    root(27, 3)

Would it be possible to reverse it?

**Comment by tmokenc** [comment]
Sure, I will change the order of the root's parameter
