### ISSUE TITLE
Constants in the evaluate function

### ISSUE THREAD

**Issue by TheRetikGM** [FIT-IVS-segmentation-fault-core-dumped/IVS-projekt-2#4]
We have talked about this in school, however I do not remember what conclusion we have reached. As such I would like to establish it here.

The question is: _How should we notate the constants in evaluate string?_
I have some suggestions:
- a) Replace the constants with value _before_ passing it to the evaluate function
- b) Constants would be functions without arguments: `evaluate("pi()")` or `evaluate("e()")`
- c) Constants would be noted with just (maybe capital) `pi` or `e`

I would prefer the `b` option, because it wouldn't get mixed up with other  parts of the string (such as `evaluate("PIpow(2, 3)"` compared to `evaluate("pi()pow(2, 3)")`). Also, it would allow the math library to choose it's own precision for given constants, compared to the `a` option.

**Comment by tmokenc** [comment]
Constants themselves aren't functions, so it's will be confusing if we using it like a function. Additionally, it should not be case-sensitive.

The math library itself can be use outside of this project, so I think that it's better to go for the `c` option.

You are right that in algebraic notation, which remove the multiplication sign between two variables, is problematic. The `b` option completely solves this problem. If we go for `a` or `c` option, we have to add a rule that the multiplication sign cannot be hidden between variables/functions.

I'm currently working on the token parser for `evaluate` function that automatically replace constant keyword with its value, it also allows users to define their own constants. (e.g. the `ANS` contant). And that's basically the option `c` in this case. But it's just my opinion.

So the `a` option is out of question, the `b` option just gives weird feeling of using constants, the `c` option removes the ability to use algebraic notation for multiplication.

How about @Blazeo7, what is your opinion on this case? Then we can go for majority opinion.

**Comment by Blazeo7** [comment]
I do not see any problem with constants being defined as functions. Also, losing ability to use algebraic notation in conjunction with constants would not be too much convenient approach. As well, we agreed to support user defined constants, therefore I do not see how `c` option could possibly work if math lib should not be aware of values defined out of its scope. 

So the `b` option seems to be the most appropriate, in my opinion.

**Comment by tmokenc** [comment]
OK we are going for the `b` option then.
